-- MySQL Script generated by MySQL Workbench
-- Fri Apr 21 15:25:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IN-RH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IN-RH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IN-RH` DEFAULT CHARACTER SET utf8 ;
USE `IN-RH` ;

-- -----------------------------------------------------
-- Table `IN-RH`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`Empleados` (
  `idEmpleados` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(1) NOT NULL,
  `fNac` DATE NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `NSS` VARCHAR(15) NOT NULL,
  `RFC` VARCHAR(15) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `numE` VARCHAR(5) NOT NULL,
  `numI` VARCHAR(5) NOT NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `CP` VARCHAR(8) NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IN-RH`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`Departamentos` (
  `idDepartamentos` INT NOT NULL AUTO_INCREMENT,
  `nameDepto` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `Empleados_idEmpleados` INT NULL,
  PRIMARY KEY (`idDepartamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IN-RH`.`Vacantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`Vacantes` (
  `idVacantes` INT NOT NULL AUTO_INCREMENT,
  `nameVacante` VARCHAR(45) NOT NULL,
  `description` TEXT(255) NOT NULL,
  `salario` FLOAT NOT NULL,
  `requisitos` VARCHAR(255) NOT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  `Departamentos_idDepartamentos` INT NOT NULL,
  PRIMARY KEY (`idVacantes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IN-RH`.`Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`Solicitudes` (
  `idSolicitudes` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cv` VARCHAR(45) NULL,
  `presentation` VARCHAR(45) NULL,
  `Vacantes_idVacantes` INT NOT NULL,
  PRIMARY KEY (`idSolicitudes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IN-RH`.`Contratacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`Contratacion` (
  `idContratacion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `salario` FLOAT NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `horaEntrada` VARCHAR(5) NOT NULL,
  `horaSalida` VARCHAR(5) NOT NULL,
  `Puestos_idPuestos` INT NOT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`idContratacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IN-RH`.`Historial_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`Historial_laboral` (
  `idHistorial_laboral` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `salario` FLOAT NULL,
  `motivos` VARCHAR(255) NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`idHistorial_laboral`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IN-RH`.`Emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`Emergencia` (
  `idEmergencia` INT NOT NULL AUTO_INCREMENT,
  `nameEmer` VARCHAR(50) NOT NULL,
  `parentesco` VARCHAR(45) NOT NULL,
  `phoneEmer` VARCHAR(15) NOT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`idEmergencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IN-RH`.`foto_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`foto_empleado` (
  `idfoto_empleado` INT NOT NULL AUTO_INCREMENT,
  `namePhoto` VARCHAR(45) NOT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`idfoto_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IN-RH`.`Organigrama`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`Organigrama` (
  `idOrganigrama` INT NOT NULL AUTO_INCREMENT,
  `jefe` INT NOT NULL,
  `empleado` INT NOT NULL,
  PRIMARY KEY (`idOrganigrama`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IN-RH`.`Formacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`Formacion` (
  `idFormacion` INT NOT NULL AUTO_INCREMENT,
  `nombreCarrera` VARCHAR(60) NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NULL,
  `escuela` VARCHAR(60) NOT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`idFormacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IN-RH`.`Evaluaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`Evaluaciones` (
  `idEvaluaciones` INT NOT NULL AUTO_INCREMENT,
  `nombreEvaluacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEvaluaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IN-RH`.`PreguntasEvaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`PreguntasEvaluacion` (
  `idPreguntasEvaluacion` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(255) NOT NULL,
  `Evaluaciones_idEvaluaciones` INT NOT NULL,
  PRIMARY KEY (`idPreguntasEvaluacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IN-RH`.`Evaluaciones_has_Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IN-RH`.`Evaluaciones_has_Empleados` (
  `status` TINYINT NOT NULL DEFAULT 0,
  `Empleados_idEmpleados` INT NOT NULL,
  `Evaluaciones_idEvaluaciones` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
